background: center / cover no-repeat url("/background.png") fixed

excluded_entities:

button_card_templates: !include /config/lovelace/button_card_templates.yaml

custom_header:
  compact_mode: true
  voice_hide: true

views:
  - !include /config/lovelace/views/viewMain.yaml
  - !include /config/lovelace/views/viewLights.yaml
  - !include /config/lovelace/views/viewMedia.yaml
  - !include /config/lovelace/views/viewMaintenance.yaml
